import type {
  ActivityEvent,
  MaintenanceTask,
  MonitoredApplication,
  ServerMetric,
} from "@/lib/domain";

export const applications: MonitoredApplication[] = [
  {
    id: "thermidor",
    name: "Thermidor Agency",
    environment: "production",
    status: "healthy",
    url: "https://thermidor.agency",
    githubRepository: "thermidor/agency",
    githubBranch: "main",
    repositoryCommit: "e7d2a91f4c63b18fd098a4b79ae679d456db2f01",
    uptime30d: 99.98,
    latencyMs: 184,
    lastCheckLabel: "il y a 38 secondes",
    lastCheckStatus: "healthy",
    lastRepositoryScanLabel: "02/09/2026 09:12",
    productionDeployment: {
      commitSha: "e7d2a91f4c63b18fd098a4b79ae679d456db2f01",
      shortCommit: "e7d2a91",
      deployedAtLabel: "1 sept. à 18:42",
      source: "github-actions",
      matchesRepositoryHead: true,
    },
    technologies: [
      { name: "Next.js", version: "16", source: "confirmed" },
      { name: "Node.js", version: "24", source: "detected", evidence: ".nvmrc" },
    ],
    dependencies: [],
  },
  {
    id: "atelier",
    name: "Atelier Nord",
    environment: "production",
    status: "healthy",
    url: "https://atelier-nord.fr",
    githubRepository: "thermidor/atelier-nord",
    githubBranch: "main",
    repositoryCommit: "31de84a17c8a57cb05d5f790f14fca3898916cc3",
    uptime30d: 100,
    latencyMs: 126,
    lastCheckLabel: "il y a 42 secondes",
    lastCheckStatus: "healthy",
    lastRepositoryScanLabel: "02/09/2026 09:11",
    technologies: [
      { name: "Astro", version: "5", source: "detected", evidence: "package.json" },
    ],
    dependencies: [],
  },
  {
    id: "lumen",
    name: "Lumen Studio",
    environment: "staging",
    status: "warning",
    url: "https://staging.lumen.studio",
    githubRepository: "thermidor/lumen-studio",
    githubBranch: "develop",
    repositoryCommit: "fb072c5f7c42961b5e72b34d1accc9ca344b31c0",
    uptime30d: 99.72,
    latencyMs: 842,
    lastCheckLabel: "il y a 51 secondes",
    lastCheckStatus: "warning",
    lastRepositoryScanLabel: "02/09/2026 09:10",
    technologies: [
      { name: "Nuxt", version: "4", source: "confirmed" },
      { name: "PostgreSQL", version: "16", source: "declared" },
    ],
    dependencies: [],
  },
];

export const serverMetrics: ServerMetric[] = [
  {
    id: "cpu",
    label: "CPU",
    value: 24,
    displayValue: "24 %",
    detail: "Charge 0,62 · 4 vCPU",
    status: "healthy",
  },
  {
    id: "memory",
    label: "Mémoire",
    value: 61,
    displayValue: "4,9 / 8 Go",
    detail: "Stable depuis 6 heures",
    status: "healthy",
  },
  {
    id: "disk",
    label: "Disque",
    value: 73,
    displayValue: "58 / 80 Go",
    detail: "+4,2 Go sur 30 jours",
    status: "warning",
  },
  {
    id: "swap",
    label: "Swap",
    value: 8,
    displayValue: "164 Mo",
    detail: "Aucune pression mémoire",
    status: "healthy",
  },
];

export const maintenanceTasks: MaintenanceTask[] = [
  {
    id: "task-disk",
    applicationId: null,
    title: "Examiner la croissance du disque",
    category: "capacity",
    severity: "medium",
    dueLabel: "avant le 8 septembre",
    source: "VPS production",
    applicationName: "VPS production",
    status: "open",
    createdLabel: "3 septembre 2026",
  },
  {
    id: "task-nuxt",
    applicationId: "app-lumen",
    title: "Valider la mise à jour Nuxt 4.2",
    category: "dependency",
    severity: "low",
    dueLabel: "cette semaine",
    source: "Lumen Studio · Renovate",
    applicationName: "Lumen Studio",
    status: "planned",
    createdLabel: "2 septembre 2026",
  },
  {
    id: "task-backup",
    applicationId: null,
    title: "Planifier le test de restauration",
    category: "backup",
    severity: "medium",
    dueLabel: "dans 12 jours",
    source: "Récurrence trimestrielle",
    applicationName: "VPS production",
    status: "open",
    createdLabel: "1 septembre 2026",
  },
];

export const activity: ActivityEvent[] = [
  {
    id: "evt-check",
    title: "Collecte terminée",
    detail: "3 applications et le VPS ont répondu.",
    timeLabel: "10:42",
    status: "healthy",
  },
  {
    id: "evt-lumen",
    title: "Latence élevée sur Lumen Studio",
    detail: "842 ms pendant trois contrôles consécutifs.",
    timeLabel: "10:39",
    status: "warning",
  },
  {
    id: "evt-renovate",
    title: "Analyse des dépendances reçue",
    detail: "Une mise à jour nécessite une validation.",
    timeLabel: "09:16",
    status: "healthy",
  },
];
